package ca.ubc.cs.beta.aclib.initialization;

import ca.ubc.cs.beta.aclib.configspace.ParamConfiguration;


public interface InitializationProcedure extends Runnable
{

	/**
	 * After running this procedure
	 * @post Incumbent has the most number of runs in the run history object
	 * @post Instance Seeds that appear in Run History object will NOT be generated by instance seed generator again
	 *  
	 */
	public void run();
	
	/**
	 * 
	 * @return incumbent selected
	 */
	public ParamConfiguration getIncumbent();

	
	
	
}
